

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - echo "Installation of the repository"
  - pip install .
  - pip install python-coveralls  # Add me to install python-coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - echo "Downloading Sentry DNS file"
  - curl https://www.neuro.polymtl.ca/_media/downloads/stats_dsn_axondeepseg.txt -o AxonDeepSeg/.adsconfig
  - echo "Launch testing suite"
  - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
after_success:
  - coveralls
