

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - echo "Installation of the repository"
  - pip install .
  
# command to run tests
script:
  - echo "Launch general integrity test"
  - axondeepseg_test
